version: 1
services:
  - type: web
    name: Farm-fresh-website-Jenkosy-static-Project
    env: static
    staticSite: true
    publishDir: ./Farmfresh-JenProject.html   # or the directory containing your static files 